import express from 'express';
import multer from 'multer';
const router = express.Router();
import * as staffController from '../controllers/staffController.js';
import * as dmsStockController from '../controllers/dmsStockController.js';
import * as currentStockController from '../controllers/currentStockController.js';
import * as physicalStockController from '../controllers/physicalStockController.js';
import * as purchaseRequisitionController from '../controllers/purchaseRequisitionController.js';

const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 15 * 1024 * 1024 },
});

router.post('/', staffController.createStaff);
router.post('/upload-document', upload.single('file'), staffController.uploadStaffDocument);
router.get('/', staffController.getStaff);
router.get('/search', staffController.searchStaff);
router.get('/credits/pending', staffController.getPendingCredits);
router.post('/credits/take', staffController.recordTakenBills);
router.post('/credits/return', staffController.returnTakenBills);
router.get('/credits/taken', staffController.getTakenBillsReport);
router.get('/credits/:paymentId/remarks', staffController.getCreditRemarks);
router.put('/credits/:paymentId/remarks', staffController.updateCreditRemarks);
router.get('/bank-deposits', staffController.getBankDeposits);
router.post('/bank-deposits', staffController.createBankDeposit);
router.get('/bank-deposits/stores', staffController.searchDeliveredStores);
router.get('/bank-deposits/pending-cheques', staffController.searchPendingCheques);
router.get('/bank-deposits/upi-invoices', staffController.searchUpiInvoices);
router.put('/bank-deposits/:depositId', staffController.updateBankDeposit);
router.delete('/bank-deposits/:depositId', staffController.deleteBankDeposit);
router.get('/purchase-sellers', staffController.searchPurchaseSellers);
router.get('/purchase-sellers/company/:companyId', staffController.getPurchaseSellersByCompany);
router.get('/companies', staffController.getCompanies);
router.post('/companies', staffController.createCompany);
router.put('/companies/:id', staffController.updateCompany);
router.delete('/companies/:id', staffController.deleteCompany);
router.post('/purchase-sellers', staffController.savePurchaseSeller);
router.put('/purchase-sellers/:sellerId', staffController.updatePurchaseSeller);
router.delete('/purchase-sellers/:sellerId', staffController.deletePurchaseSeller);
router.get('/seller-items', staffController.getSellerItems);
router.post('/seller-items', staffController.createSellerItem);
router.put('/seller-items/:itemId', staffController.updateSellerItem);
router.delete('/seller-items/:itemId', staffController.deleteSellerItem);
router.get('/purchases', staffController.getPurchases);
router.post('/purchases', staffController.createPurchase);
router.put('/purchases/:purchaseId', staffController.updatePurchase);
router.delete('/purchases/:purchaseId', staffController.deletePurchase);
router.get('/purchase-reports', staffController.getPurchaseReports);
router.post('/purchase-requisitions', purchaseRequisitionController.create);
router.get('/purchase-requisitions', purchaseRequisitionController.list);
router.get('/purchase-requisitions/:number', purchaseRequisitionController.getByNumber);
router.get('/dms-stock', dmsStockController.getLatestDmsStock);
router.get('/dms-stock/imports', dmsStockController.getDmsStockImports);
router.get('/dms-stock/product-search', dmsStockController.searchDmsStockProducts);
router.get('/dms-stock/product-lookup', dmsStockController.lookupDmsStockProduct);
router.post('/dms-stock/upload', upload.single('file'), dmsStockController.uploadDmsStock);
router.post('/dms-stock/manual', dmsStockController.createManualDmsStock);
router.put('/dms-stock/items/:itemId', dmsStockController.updateDmsStockItem);
router.delete('/dms-stock/items/:itemId', dmsStockController.deleteDmsStockItem);
router.get('/current-stock', currentStockController.getCurrentStock);
router.get('/physical-stock', physicalStockController.getPhysicalStock);
router.get('/physical-stock/company', physicalStockController.getPhysicalStockForCompany);
router.get('/physical-stock/dms-products', physicalStockController.getPhysicalStockDmsProducts);
router.get('/physical-stock/product-lookup', physicalStockController.lookupPhysicalStockProduct);
router.get('/physical-stock/item-history', physicalStockController.getPhysicalStockItemHistory);
router.post('/physical-stock/upload', upload.single('file'), physicalStockController.uploadPhysicalStock);
router.post('/physical-stock/manual', physicalStockController.createManualPhysicalStock);
router.post('/physical-stock/approve', physicalStockController.approvePhysicalStockFromDms);
router.get('/sales/by-date', staffController.getAllSalesByDate);
router.get('/sales/lookup', staffController.lookupSaleByInvoice);
router.get('/sales/cancelled', staffController.getCancelledDeliverySales);
router.get('/reports', staffController.getReports);
router.get('/:id', staffController.getStaffFullDetails);
router.put('/:id', staffController.updateStaff);
router.put('/:id/toggle-active', staffController.toggleStaffActive);
router.get('/:id/locations', staffController.getStaffLocations);
router.get('/:id/outlets-by-date', staffController.getOutletsByStaffAndDate);
router.get('/:id/all-counters', staffController.getAllOutletsForStaff);
router.get('/:id/outlets-by-day', staffController.getOutletsByStaffAndDayName);
router.post('/:id/counters', staffController.addCounter);
router.post('/:id/sales', staffController.recordSales);
router.get('/:id/next-bill-number', staffController.getNextBillNumber);
router.get('/:id/sales-by-date', staffController.fetchSalesByDate);
router.put('/counter/:counterId', staffController.editCounter);
router.delete('/counter/:counterId', staffController.deleteCounter);
router.put('/sales/:saleId/payment', staffController.updatePaymentMode);
router.get('/sales/:saleId/payments', staffController.getSalePayments);
router.get('/sales/:saleId/status-history', staffController.getSaleStatusHistory);
router.post('/sales/:saleId/payments', staffController.addSalePayment);

router.put('/sales/:saleId/payments/:paymentId', staffController.editSalePayment);
router.delete('/sales/:saleId/payments/:paymentId', staffController.deleteSalePayment);

router.put('/sales/:saleId', staffController.updateSale);
router.delete('/sales/:saleId', staffController.deleteSale);
router.put('/sales/:saleId/packaging', staffController.updatePackagingStatus);
router.post('/sales/:saleId/cancel-log', staffController.logOrderCancellation);
router.get('/sales/:saleId/cancel-log', staffController.getOrderCancellations);

export default router;
